/**
 * Created by ling xue on 2016/3/2.
 */

/**
 * USER REQUEST TYPE
 */
var USER_REQUEST_HEAD_CLIENT = "client-id";

/**
 * USER REGISTRIATION METHOD
 */
var USER_AUTH_PHONEPASSWORD = "phonepassword";
var USER_AUTH_USERNAMEPASSWORD = "usernamepassword";
var USER_AUTH_EMAILPASSWORD = "emailpassword";
var USER_AUTH_WECHAT = "wechat";
var USER_AUTH_TOKEN = "token";

/**
 * Reset password method
 */
var RESETPWD_PHONE = "phone";
var RESETPWD_USERID = "userid";

/**
 * USER STATUS
 */
var USER_STATUS_ACTIVE = 1;
var USER_STATUS_NOT_ACTIVE = 0;

/**
 * USER WECHAT STATUS
 */
var USER_WECHAT_STATUS_ACTIVE = 1;
var USER_WECHAT_STATUS_NOT_ACTIVE = 0;

var PERMISSION_CREATE_TENANTS = "createTenants";
var PERMISSION_UPDATE_TENANTS = "updateTenants";
var PERMISSION_DELETE_TENANTS = "deleteTenants";
var PERMISSION_CREATE_USERS = "createUsers";
var PERMISSION_GET_USERS = "getUsers";
var PERMISSION_DELETE_USERS = "deleteUsers";
var PERMISSION_UPDATE_USERS = "updateUsers";
var PERMISSION_CREATE_ROLES = "createRoles";
var PERMISSION_DELETE_ROLES = "deleteRoles";
var PERMISSION_CREATE_BIZ_USERS = "createBizUsers";
var PERMISSION_GET_BIZ_USERS = "getBizUsers";
var PERMISSION_DELETE_BIZ_USERS = "deleteBizUsers";
var PERMISSION_UPDATE_BIZ_USERS = "updateBizUsers";
var PERMISSION_ASSIGN_BIZ_USERROLES ="assignBizUserRoles"
var PERMISSION_CREATE_PERMISSIONS = "createPermissions";
var PERMISSION_DELETE_PERMISSIONS = "deletePermissions";
var PERMISSION_GET_PERMISSIONS = "getPermissions";
var PERMISSION_ASSIGN_USERROLES = "assignUserRoles";
var PERMISSION_ASSIGN_ROLEPERMISSIONS = "assignRolePermissions";
var PERMISSION_UPDATE_PERMISSIONS ="updatePermissions";
var PERMISSION_UPDATE_ROLES="updateRoles";


/**
 * SMS SEND TYPE
 */
var SMS_REG_TYPE = "registeruser";
var SMS_PSWD_TYPE = "resetpassword";
var SMS_PHONE_TYPE = "changephone";//修改手机号

/**
 * CAPTCHA TYPE
 */

var EXPIRED_TIME_CAPTCHA = 300;

var EXPIRED_TIME_REG_SMS = 900;

var EXPIRED_TIME_PSWD_SMS = 900;

var EXPIRED_TIME_PHONE_SMS = 900;

var  EXPIRED_TIME_ACTIVEUSER_EMAIL = 86400;

var CACHE_APPEND_CPATCHA = "CPA_";

var CACHE_APPEND_REG = "REG_";

var CACHE_APPEND_RESETPWD = "RESETPWD_";

var CACHE_APPEND_CHANGPHONE = "CHGPHONE_";

var CACHE_APPEND_EMAILACTIVEUSER = "EMAILACTIVEUSER_"

/**
 * EMAIL SEND TYPE
 */
var EMAIL_ACTIVEUSER_TYPE = "activateuser";
var EMAIL_PSWD_TYPE = "resetpassword";
var EMAIL_EMAIL_TYPE = "changeeamil";

/**
 * OAUTH USER GROUP
 *
 */


var USER_TYPE_USER = "user"; //end user
var USER_TYPE_INTERNAL = "internal"; //后台管理员
var USER_TYPE_SYSTEM = "system"; //system module

var ROLE_AMDIN = "admin";


module.exports = {
    USER_REQUEST_HEAD_CLIENT: USER_REQUEST_HEAD_CLIENT,
    USER_STATUS_ACTIVE: USER_STATUS_ACTIVE,
    USER_STATUS_NOT_ACTIVE: USER_STATUS_NOT_ACTIVE,

    SMS_REG_TYPE: SMS_REG_TYPE,
    SMS_PSWD_TYPE: SMS_PSWD_TYPE,
    SMS_PHONE_TYPE: SMS_PHONE_TYPE,

    EMAIL_ACTIVEUSER_TYPE:EMAIL_ACTIVEUSER_TYPE,
    EMAIL_PSWD_TYPE : EMAIL_PSWD_TYPE,
    EMAIL_EMAIL_TYPE : EMAIL_EMAIL_TYPE,

    EXPIRED_TIME_CAPTCHA: EXPIRED_TIME_CAPTCHA,
    EXPIRED_TIME_REG_SMS: EXPIRED_TIME_REG_SMS,
    EXPIRED_TIME_PSWD_SMS: EXPIRED_TIME_PSWD_SMS,
    EXPIRED_TIME_PHONE_SMS: EXPIRED_TIME_PHONE_SMS,
    EXPIRED_TIME_ACTIVEUSER_EMAIL:  EXPIRED_TIME_ACTIVEUSER_EMAIL,

    CACHE_APPEND_CPATCHA: CACHE_APPEND_CPATCHA,
    CACHE_APPEND_REG: CACHE_APPEND_REG,
    CACHE_APPEND_RESETPWD: CACHE_APPEND_RESETPWD,
    CACHE_APPEND_CHANGPHONE: CACHE_APPEND_CHANGPHONE,
    CACHE_APPEND_EMAILACTIVEUSER:CACHE_APPEND_EMAILACTIVEUSER,

    RESETPWD_PHONE: RESETPWD_PHONE,
    RESETPWD_USERID: RESETPWD_USERID,

    USER_TYPE_USER: USER_TYPE_USER,
    USER_TYPE_INTERNAL: USER_TYPE_INTERNAL,
    USER_TYPE_SYSTEM: USER_TYPE_SYSTEM,

    USER_WECHAT_STATUS_ACTIVE: USER_WECHAT_STATUS_ACTIVE,
    USER_WECHAT_STATUS_NOT_ACTIVE: USER_WECHAT_STATUS_NOT_ACTIVE,

    USER_AUTH_PHONEPASSWORD: USER_AUTH_PHONEPASSWORD,
    USER_AUTH_EMAILPASSWORD: USER_AUTH_EMAILPASSWORD,
    USER_AUTH_WECHAT: USER_AUTH_WECHAT,
    USER_AUTH_TOKEN: USER_AUTH_TOKEN,
    USER_AUTH_USERNAMEPASSWORD: USER_AUTH_USERNAMEPASSWORD,

    ROLE_AMDIN: ROLE_AMDIN,

    PERMISSION_CREATE_TENANTS: PERMISSION_CREATE_TENANTS,
    PERMISSION_UPDATE_TENANTS: PERMISSION_UPDATE_TENANTS,
    PERMISSION_DELETE_TENANTS: PERMISSION_DELETE_TENANTS,
    PERMISSION_CREATE_USERS: PERMISSION_CREATE_USERS,
    PERMISSION_GET_USERS: PERMISSION_GET_USERS,
    PERMISSION_UPDATE_USERS: PERMISSION_UPDATE_USERS,
    PERMISSION_DELETE_USERS: PERMISSION_DELETE_USERS,
    PERMISSION_CREATE_BIZ_USERS: PERMISSION_CREATE_BIZ_USERS,
    PERMISSION_GET_BIZ_USERS: PERMISSION_GET_BIZ_USERS,
    PERMISSION_UPDATE_BIZ_USERS: PERMISSION_UPDATE_BIZ_USERS,
    PERMISSION_DELETE_BIZ_USERS: PERMISSION_DELETE_BIZ_USERS,
    PERMISSION_CREATE_ROLES: PERMISSION_CREATE_ROLES,
    PERMISSION_CREATE_PERMISSIONS: PERMISSION_CREATE_PERMISSIONS,
    PERMISSION_GET_PERMISSIONS: PERMISSION_GET_PERMISSIONS,
    PERMISSION_DELETE_PERMISSIONS:PERMISSION_DELETE_PERMISSIONS,
    PERMISSION_ASSIGN_USERROLES: PERMISSION_ASSIGN_USERROLES,
    PERMISSION_ASSIGN_ROLEPERMISSIONS: PERMISSION_ASSIGN_ROLEPERMISSIONS,
    PERMISSION_ASSIGN_BIZ_USERROLES:PERMISSION_ASSIGN_BIZ_USERROLES,
    PERMISSION_UPDATE_PERMISSIONS:PERMISSION_UPDATE_PERMISSIONS,

    PERMISSION_UPDATE_ROLES:PERMISSION_UPDATE_ROLES,
    PERMISSION_DELETE_ROLES:PERMISSION_DELETE_ROLES
};
